apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 # Vous pouvez ajuster le nombre de répliques selon vos besoins
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rg.fr-par.scw.cloud/campus/sante-backend # Remplacez par votre image Docker
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILE
          value: rec